const jCategory = [
    {
        index:0,
        image:"/JSTACK-Job-Portal-Website-main/images/google.png",
        title:"Web Developer",
        rate:"$900-1200/m",
        av:"Full Time",
        companyName:"Google",
        location:"USA",
        vacancy:"01",
        hours:"50h / week",
        description:"Google is a global technology company that specializes in internet-related services and products. Founded in 1998, Google is best known for its search engine, but it also offers a wide range of tools and platforms including Gmail, Google Maps, YouTube, Google Drive, and the Android operating system. As a subsidiary of Alphabet Inc., Google leads innovation in artificial intelligence, cloud computing, and digital advertising, shaping how people interact with information and technology worldwide.",
        workplace:"Work from Home",
        education:"Bachelor degree in any computer science course.",
        experience:"2 to 5 year(s)",
    },


     {
        index:1,
        image:"/JSTACK-Job-Portal-Website-main/images/uber.png",
        title:"Business Associate",
        rate:"$900-1200/m",
        av:"Freelancer",
         companyName:"Uber",
        location:"USA",
        vacancy:"04",
        hours:"40h / week",
        description:"Uber is a global technology company that revolutionized transportation by introducing a ride-hailing platform that connects riders with drivers through a mobile app. Founded in 2009, Uber has expanded its services to include food delivery (Uber Eats), freight shipping, and autonomous vehicle development. Operating in over 70 countries, Uber aims to make transportation more accessible, efficient, and sustainable through innovation and smart mobility solutions.",
         workplace:"Work from Home",
        education:"Bachelor degree in any computer science course.",
        experience:"1 to 5 year(s)",
    
    },

     {
        index:2,
        image:"/JSTACK-Job-Portal-Website-main/images/linkedin.png",
        title:"Business Associate",
        rate:"$900-1200/m",
        av:"Full Time",
        companyName:"Linkedin",
        location:"Canada",
        vacancy:"05",
        hours:"60h / week",
        description:"Uber is a global technology company that revolutionized transportation by introducing a ride-hailing platform that connects riders with drivers through a mobile app. Founded in 2009, Uber has expanded its services to include food delivery (Uber Eats), freight shipping, and autonomous vehicle development. Operating in over 70 countries, Uber aims to make transportation more accessible, efficient, and sustainable through innovation and smart mobility solutions.",
         workplace:"Work from Home",
        education:"Bachelor degree in any computer science course.",
        experience:"3 to 5 year(s)",
    
    },
     {
        index:3,
        image:"/JSTACK-Job-Portal-Website-main/images/instagram.png",
        title:"Product Designer",
        rate:"$900-1200/m",
        av:"Full Time",
        companyName:"Instagram",
        location:"Canada",
        vacancy:"05",
        hours:"60h / week",
        description:"Uber is a global technology company that revolutionized transportation by introducing a ride-hailing platform that connects riders with drivers through a mobile app. Founded in 2009, Uber has expanded its services to include food delivery (Uber Eats), freight shipping, and autonomous vehicle development. Operating in over 70 countries, Uber aims to make transportation more accessible, efficient, and sustainable through innovation and smart mobility solutions.",
         workplace:"Work from Home",
        education:"Bachelor degree in any computer science course.",
        experience:"3 to 5 year(s)",
     },
      {
        index:4,
        image:"/JSTACK-Job-Portal-Website-main/images/facebook.png",
        title:"Digital Marketing",
        rate:"$900-1200/m",
        av:"Full Time",
        companyName:"Facebook",
        location:"USA",
        vacancy:"05",
        hours:"60h / week",
        description:"Uber is a global technology company that revolutionized transportation by introducing a ride-hailing platform that connects riders with drivers through a mobile app. Founded in 2009, Uber has expanded its services to include food delivery (Uber Eats), freight shipping, and autonomous vehicle development. Operating in over 70 countries, Uber aims to make transportation more accessible, efficient, and sustainable through innovation and smart mobility solutions.",
         workplace:"Work from Home",
        education:"Bachelor degree in any computer science course.",
        experience:"2 to 5 year(s)",
     },
      {
        index:5,
        image:"/JSTACK-Job-Portal-Website-main/images/yahoo.png",
        title:"User Experience",
        rate:"$900-1200/m",
        av:"Full Time",
        companyName:"Yahoo",
        location:"Canada",
        vacancy:"05",
        hours:"60h / week",
        description:"Uber is a global technology company that revolutionized transportation by introducing a ride-hailing platform that connects riders with drivers through a mobile app. Founded in 2009, Uber has expanded its services to include food delivery (Uber Eats), freight shipping, and autonomous vehicle development. Operating in over 70 countries, Uber aims to make transportation more accessible, efficient, and sustainable through innovation and smart mobility solutions.",
         workplace:"Work from Home",
        education:"Bachelor degree in any computer science course.",
        experience:"3 to 5 year(s)",
     },
     
];
